	# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../Instruct.rb'
vagrant_api_version = 2
project = "simbuild"
cluster = {
	"box" => { :ip => "192.168.12.203", :mem => 1024, :box => "centos/7", :instructType => "podbuild"},
	"amz2" => { :ip => "192.168.12.204", :mem => 1024, :box => "winky/amazonlinux-2", :instructType => "podbuild"},

}


puts "variables init"
Vagrant.configure(vagrant_api_version) do |config|
	cluster.each_with_index do |(boxId, info), index|
        Instruct.new.send(info[:instructType], cluster, project, boxId, config)
	end        
end
