# -*- mode: ruby -*-
# vi: set ft=ruby :

# require 'yaml'
# settings = YAML.load_file 'vagrant.yml'
# vagrant_api_version = settings[vagrant_api_version]
# project = settings["project"]
# cluster = settings["cluster"]

vagrant_api_version = 2
project = "servers"
cluster = {
  "1" => { :ip => "192.168.12.210", :cpus => 1, :mem => 1024, :box => "centos700"},
  "2" => { :ip => "192.168.12.211", :cpus => 1, :mem => 1024, :box => "centos700"}
}
puts "variables init"
Vagrant.configure(vagrant_api_version) do |config|
	cluster.each_with_index do |(boxId, info), index|
		boxName = project + "." + info[:box] + "." + boxId
		config.vm.define boxName do |node|
			node.vm.box = info[:box]
			# node.vm.hostname = boxName
			node.vm.box_url = "http://vagrant/" + project + "/" + info[:box] + "/" + boxId
			node.vm.network "private_network", ip: info[:ip]
			# node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
			node.vm.synced_folder ".", '/home/vagrant/sync', disabled: true
			# node.vm.provision "shell", inline: "ifup enp0s8", run: "always"
			# Port forwarding
			# config.vm.network "forwarded_port", guest: 80, host: 8080 # HTTP
			# config.vm.network "forwarded_port", guest: 443, host: 4443 # HTTPS
			node.vm.provider :virtualbox do |v|
				v.memory = info[:mem]
				v.name = boxName
			end
			puts boxId + "of the cluster is up"
		end
	end
end
