	# -*- mode: ruby -*-
# vi: set ft=ruby :


require_relative '../Instruct'
vagrant_api_version = 2
project = "docker"
cluster = {
	"unit" => { :ip => "192.168.12.221", :mem => 1024, :box => "centos/7", :instructType => "common", :alias => "docker"}
}

puts "variables init"
Vagrant.configure(vagrant_api_version) do |config|
	cluster.each_with_index do |(boxId, info), index|
        Instruct.new.send(info[:instructType], cluster, project, boxId, config)
	end        
end
