	# -*- mode: ruby -*-
# vi: set ft=ruby :


require_relative '../Instruct'
vagrant_api_version = 2
project = "nginx"
cluster = {
	"1" => { :ip => "192.168.1.2", :mem => 1024, :box => "centos/7", :instructType => "common", :alias => "nginx"}
}

puts "variables init"
Vagrant.configure(vagrant_api_version) do |config|
	cluster.each_with_index do |(boxId, info), index|
        Instruct.new.send(info[:instructType], cluster, project, boxId, config)
	end        
end
