	# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../Instruct.rb'
vagrant_api_version = 2
project = "bootloader"
cluster = {
	"ubuntu" => { :ip => "192.168.12.205", :mem => 4096, :box => "ubuntu/trusty64", :instructType => "common",  :alias => "ubuntu1"},
}


puts "variables init"
Vagrant.configure(vagrant_api_version) do |config|
	cluster.each_with_index do |(boxId, info), index|
        Instruct.new.send(info[:instructType], cluster, project, boxId, config)
	end        
end
